apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: vertex-ai-cloud-deploy-pipeline
serialPipeline:
  stages:
  - targetId: dev-endpoint
    strategy:
      standard:
        postdeploy:
          actions: ["add-aliases"]
  - targetId: staging-endpoint
    strategy:
      standard:
        postdeploy:
          actions: ["add-aliases"]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-endpoint
customTarget:
  customTargetType: vertex-ai-endpoint
deployParameters:
  customTarget/vertexAIEndpoint: "projects/$PROJECT_ID/locations/$REGION/endpoints/$DEV_ENDPOINT_ID"
  customTarget/vertexAIConfigurationPath: "dev/deployedModel.yaml"
  customTarget/vertexAIMinReplicaCount: "3"
  customTarget/vertexAIAliases: "dev"
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
requireApproval: true
metadata:
  name: staging-endpoint
customTarget:
  customTargetType: vertex-ai-endpoint
deployParameters:
  customTarget/vertexAIEndpoint: "projects/$PROJECT_ID/locations/$REGION/endpoints/$STAGING_ENDPOINT_ID"
  customTarget/vertexAIConfigurationPath: "staging/deployedModel.yaml"
  customTarget/vertexAIMinReplicaCount: "3"
  customTarget/vertexAIAliases: "staging,champion"
